var subjects = {
  'bash' : [
    new Card('Mostrar Nombre de Usuario', '$ whoami'),
    new Card('Mostrar Nombre del Ordenador', '$ hostname'),
    new Card('Mostrar Directorio Actual', '$ pwd'),
    new Card('Listar Archivos del Directorio', '$ ls'),
    new Card('Listar Archivos Detallados', '$ ls -l'),
    new Card('Listar Ordenando por Fecha', '$ ls –t'),
    new Card('Listar Ordenando por Tamaño', '$ ls -S'),
    new Card('Listar Invirtiendo el Orden', '$ ls -r'),
    new Card('Listar Incluyendo Archivos Ocultos', '$ ls -a'),
    new Card('Navegar al Directorio Padre', '$ cd ..'),
    new Card('Navegar a una Carpeta Interna', '$ cd Carpeta1'),
    new Card('Navegar a una Ruta Absoluta', '$ cd /Absoluta1'),
    new Card('Navegar a la Carpeta Root', '$ cd /'),
    new Card('Navegar a la Carpeta Home', '$ cd ~'),
    new Card('Navegar a la Carpeta Anterior', '$ cd -'),
    new Card('Crear Nueva Carpeta', '$ mkdir Carpeta1'),
    new Card('Eliminar Carpeta', '$ rmdir Carpeta1'),
    new Card('Crear Nuevo Archivo', '$ touch Archivo1'),
    new Card('Borrar Archivo', '$ rm Archivo1'),
    new Card('Eliminar Carpeta y todos sus Archivos', '$ rm –rf Carpeta1'),
    new Card('Leer Contenido de Archivo', '$ cat Archivo1'),
    new Card('Copiar Archivo en la misma Carpeta', '$ cp Archivo1 Archivo2'),
    new Card('Copiar Archivo en otra Carpeta', '$ cp Archivo1 Carpeta1/'),
    new Card('Copiar Carpeta no Vacía', '$ cp -r Carpeta1 Carpeta2/'),
    new Card('Renombrar un Archivo', '$ mv Archivo1 Archivo2'),
    new Card('Limpiar Terminal', '$ clear')
  ],
  'git' : [
    new Card('Comprobar si GIT está Instalado', '$ git'),
    new Card('Ver Versión de GIT', '$ git --version'),
    new Card('Establecer Nombre', '$ git config --global user.name "Nombre"'),
    new Card('Establecer Email', '$ git config --global user.email me@mail.com'),
    new Card('Establecer Seguimiento de Carpeta', '$ git init'),
    new Card('Eliminar Seguimiento de Carpeta', '$ git -rf .git'),
    new Card('Ver Archivos que se están Rastreando', '$ git status'),
    new Card('Poner en Seguimiento un Archivo', '$ git add Archivo1'),
    new Card('Poner en Seguimiento varios Archivos', '$ git add Archivo1 Archivo2'),
    new Card('Poner en Seguimiento todos los Archivos', '$ git add -A'),
    new Card('Quitar del Seguimiento un Archivo', '$ git reset Archivo1'),
    new Card('Commit del Proyecto', '$ git commit -m "Mensaje1"'),
    new Card('Ver Commits del Proyecto', '$ git log'),
    new Card('Salir de la Visualización de los Commits', 'q'),
    new Card('Agregar Repositorio Remoto', '$ git remote add Alias1 https://github.com/X'),
    new Card('Ver Repositorios Remotos', '$ git remote'),
    new Card('Enviar a Repositorio Remoto', '$ git push Alias1 master'),
    new Card('Descargar de Repositorio Remoto', '$ git pull Alias1 master'),
    new Card('Clonar de Repositorio Remoto', '$ git clone https://github.com/X')
  ],
  'html' : [
    new Card('Establecer DOCTYPE', '<!DOCTYPE html>'),
    new Card('Establecer idioma en etiqueta html', '<html lang="en">\n\n...\n\n</html>'),
    new Card('Etiqueta de Cabecera', '<head>\n\n...\n\n</head>'),
    new Card('Etiqueta de Título', '<title>Titulo</title>'),
    new Card('Establecer UTF-8', '<meta charset="utf-8">'),
    new Card('Etiqueta para Sección', '<section>\n\n...\n\n</section>'),
    new Card('Etiqueta para Artículo', '<article>\n\n...\n\n</article>'),
    new Card('Etiqueta para Menú', '<nav>\n\n...\n\n</nav>'),
    new Card('Etiqueta que contiene todos los Elementos Visibles', '<body>\n\n...\n\n</body>'),
    new Card('Etiqueta para Incrustar Código CSS', '<style>\n\nselector { propiedad: valor; }\n\n</style>'),
    new Card('Vincular CSS Externo', '<link rel="stylesheet" href="style.css">'),
    new Card('Etiqueta que representa una Caja', '<div>\n\n...\n\n</div>'),
    new Card('Encabezados de Distinta Importancia', '<h1>,<h2>,<h3>,<h4>,<h5> y <h6>'),
    new Card('Etiqueta que representa Contenido Complementario', '<aside>\n\n...\n\n</aside>'),
    new Card('Etiqueta Encabezado', '<header>\n\n...\n\n</header>'),
    new Card('Etiqueta que representa Pie de Página', '<footer>\n\n...\n\n</footer>'),
    new Card('Lista Desordenada', '<ul>\n\n<li>Item1</li>\n<li>Item2</li>\n\n</ul>'),
    new Card('Lista Ordenada', '<ol>\n\n<li>Item1</li>\n<li>Item2</li>\n\n</ol>'),
    new Card('Etiqueta para Imagen', '<img src="img.jpg" alt="img">'),
    new Card('Etiqueta para Enlace', '<a href="index.html">Texto</a>'),
    new Card('Envoltura Genérica para Texto', '<span>\n\n...\n\n</span>'),
    new Card('Etiqueta para Contenido Relevante - Negrita', '<strong>\n\n...\n\n</strong>'),
    new Card('Etiqueta para Contenido Enfatizado - Cursiva', '<em>\n\n...\n\n</em>'),
    new Card('Etiqueta para Tabla', '<table>\n\n...\n\n</table>'),
    new Card('Etiqueta para Fila de una Tabla', '<tr>\n\n...\n\n</tr>'),
    new Card('Etiqueta para Columna en una Fila que es Encabezado', '<th>Encabezado1</th>'),
    new Card('Etiqueta para Columna en una Fila que es Encabezado', '<td>Elemento1</td>'),
    new Card('Etiqueta para Salto de Línea', '<br>'),
    new Card('Etiqueta para Introducir Texto en Formulario', '<input type="text" name="text1">'),
    new Card('Etiqueta para Introducir Número en Formulario', '<input type="number" name="number1">'),
    new Card('Etiqueta para Introducir Email en Formulario', '<input type="email" name="email1">'),
    new Card('Etiqueta para Introducir Fecha en Formulario', '<input type="date" name="date1">'),
    new Card('Etiqueta que Representa un Botón dentro de un Formulario', '<input type="submit">'),
    new Card('Etiqueta que Representa un Botón fuera de un Formulario', '<input type="button">Botón</button>'),
    new Card('Etiqueta para Introducir Texto en Múltiples Líneas en un Formulario', '<textarea rows="4" cols="8"></textarea>'),
    new Card('Etiqueta que Permite Marcar una Opción de Varias en un Formulario', '<input type="radio" name="rad" value="op1">Opción 1\n<input type="radio" name="rad" value="op2">Opción 2'),
    new Card('Etiqueta que Permite Marcar Varias Opciones en un Formulario', '<input type="checkbox" name="c" value="c1">Opción 1\n<input type="checkbox" name="c" value="c2">Opción 2'),
    new Card('Etiqueta que Permite Marcar una Opción de una Lista Desplegable en un Formulario', '<select name="s1">\n\n<option value="v1">Valor1</option>\n<option value="v2">Valor2</option>\n\n</select>'),
    new Card('Etiqueta que Representa un Etiquetado para Campos HTML', '<label for="c1">Campo1:</label>\n<input type="text" id="c1">')

  ],
  'css' : [
    new Card('Establecer Fuente Tipográfica', 'font-family: Arial;'),
    new Card('Establecer Tamaño de Fuente', 'font-size: 9px;'),
    new Card('Establecer Subrayado', 'text-decoration: underline;'),
    new Card('Establecer Tachado', 'text-decoration: line-through;'),
    new Card('Establecer Grueso de Línea', 'font-weight: 900;'),
    new Card('Establecer Cursiva', 'font-style: italic;'),
    new Card('Establecer Oblícua', 'font-style: oblique;'),
    new Card('Establecer Altura de Línea', 'line-height: 9px;'),
    new Card('Establecer Alineación del Texto', 'text-align: center;'),
    new Card('Convertir a Mayúsculas', 'text-transform: uppercase;'),
    new Card('Establecer Color de Fondo', 'background-color: #fff;'),
    new Card('Establecer Borde', 'border: 1px solid #fff;'),
    new Card('Establecer Estilo del Borde', 'border-style: solid;'),
    new Card('Establecer Borde Redondeado', 'border-radius: 9px;'),
    new Card('Establecer Espacio entre el Contenido y el Borde de una Caja', 'padding: 9px;'),
    new Card('Establecer Espacio entre el Borde de una Caja y otros Elementos', 'margin: 9px;'),
    new Card('Establecer una Imagen como Fondo', 'background-image: url("img.jpg");'),
    new Card('Establecer el Área que Ocupará la Imagen de Fondo', 'background-size: cover;'),
    new Card('Establecer si la Imagen de Fondo se Repetirá', 'background-repeat: no-repeat;'),
    new Card('Establecer la Distancia entre Letras', 'letter-spacing: 9px;'),
    new Card('Establecer que Border y Padding NO afecten al Ancho y al Alto Totales', 'box-sizing: border-box;'),
    new Card('Establecer Sombra en una Caja', 'box-shadow: 9px 9px 9px #fff;'),
    new Card('Establecer Posicionamiento Estático', 'position: static;'),
    new Card('Establecer Posicionamiento Relativo', 'position: relative;'),
    new Card('Establecer Posicionamiento Absoluto', 'position: absolute;'),
    new Card('Establecer Posicionamiento Fixed', 'position: fixed;'),
    new Card('Establecer que un Elemento Flote', 'float: left;'),
    new Card('Cambiar de Elemento de En Línea a Elemento En Bloque', 'display: block;'),
    new Card('Establecer Estilo de Lista', 'list-style-type: none;')
  ]
};